config/routes.rb
Rails.application.routes.draw do
  resources :merchants do
    resources :products
    resources :orders do
      collection do
        get :add_order_item
      end

      member do
        get :report
        get :invoice
      end
    end
  end

  mount ChinaCity::Engine => '/china_city'
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :merchant
  belongs_to :customer
  has_many :order_items, dependent: :destroy

  validates :merchant, presence: true
  validates :customer, presence: true

  accepts_nested_attributes_for :customer
  accepts_nested_attributes_for :order_items, allow_destroy: true

  def total_cost
    if persisted? && (!caculated_at? || caculated_at < updated_at)
      update_columns total_cost: order_items.map(&:total).sum, caculated_at: Time.now
    end
    super
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_merchant
  before_action :set_order, only: [:show, :edit, :update, :destroy, :report, :invoice]

  # GET /orders
  # GET /orders.json
  def index
    @orders = @merchant.orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = @merchant.orders.new
    @order.build_customer
    @order.order_items.build
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = @merchant.orders.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to [@merchant, @order], notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: [@merchant, @order] }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update_attributes(order_params)
        format.html { redirect_to [@merchant, @order], notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: [@merchant, @order] }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to merchant_url(@merchant), notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_order_item
    @order = Order.new
    @order_item = @order.order_items.build
    render 'add_order', layout: false
  end

  def report
    render file: 'public/report', layout: false
  end

  def invoice
    send_file 'public/invoice.pdf'
  end

  private
  def set_merchant
    @merchant = Merchant.find(params[:merchant_id])
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = @merchant.orders.includes(:customer, order_items: [:product]).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:transacted_at, customer_attributes: [:id, :name, :phone, :gender], order_items_attributes: [:id, :product_id, :quantity, :discount, :_destroy])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.slim
.panel.panel-default.order-item-form
  .panel-body
    = simple_form_for([@merchant, @order]) do |f|
      = f.error_notification
      = f.hidden_field :merchant_id

      = f.input :transacted_at, as: :string, input_html: { value: (@order.transacted_at || Time.now).to_formatted_s(:db) }

      .row
        = f.association :customer do |customer_form|
          = customer_form.hidden_field :id
          = customer_form.input :name, wrapper_html: { class: 'col-xs-8 col-md-5' }
          = customer_form.input :gender, collection: Customer.genders.map { |key, _| [Customer::GENDER[key.to_sym], key] }, include_blank: '--性别--', wrapper_html: { class: 'col-xs-4 col-md-2' }
          = customer_form.input :phone, wrapper_html: { class: 'col-xs-12 col-md-5' }

      .order-items
        = f.association :order_items do |order_item_form|
          .row.js-order-item
            = order_item_form.hidden_field :id
            = order_item_form.input :product_id, collection: @merchant.products, label_method: :name, value_method: :id, as: :select, wrapper_html: { class: 'col-md-3 col-xs-6' }, input_html: { class: 'product' }
            = order_item_form.input :price, disabled: true, wrapper_html: { class: 'col-md-2 col-xs-6' }, input_html: { class: 'price' }
            = order_item_form.input :quantity, wrapper_html: { class: 'col-md-2 col-xs-6' }, input_html: { class: 'quantity', min: 1 }
            = order_item_form.input :discount, wrapper_html: { class: 'col-md-2 col-xs-6' }, input_html: { class: 'discount', max: 1 }
            = order_item_form.input :total, disabled: true, wrapper_html: { class: 'col-md-2 col-xs-6' }, input_html: { class: 'total' }
            = order_item_form.hidden_field :_destroy, class: 'destroy'
            .form-group.col-md-1.col-xs-1
              label.control-label Actions
              = link_to 'Delete', '##', class: 'btn btn-danger destroy'

      .form-group
        p Total cost
        p.js-order-total-cost= @order.total_cost
      .form-actions
        = f.button :submit, class: 'btn btn-primary'
        = link_to 'Add order item', '##', class: 'btn btn-success pull-right js-order-item-add'

app/views/orders/add_order.slim
= simple_form_for([@merchant, @order]) do |f|
  = f.association :order_items, as: "order[order_items_attributes][#{Time.now.to_i}]" do |order_item_form|
    .row.js-order-item
      = order_item_form.hidden_field :id
      = order_item_form.input :product_id, collection: @merchant.products, label_method: :name, value_method: :id, as: :select, wrapper_html: { class: 'col-md-3 col-xs-6' }, input_html: { class: 'product' }
      = order_item_form.input :price, disabled: true, wrapper_html: { class: 'col-md-2 col-xs-6' }, input_html: { class: 'price' }
      = order_item_form.input :quantity, wrapper_html: { class: 'col-md-2 col-xs-6' }, input_html: { class: 'quantity', min: 1 }
      = order_item_form.input :discount, wrapper_html: { class: 'col-md-2 col-xs-6' }, input_html: { class: 'discount', max: 1 }
      = order_item_form.input :total, disabled: true, wrapper_html: { class: 'col-md-2 col-xs-6' }, input_html: { class: 'total' }
      = order_item_form.hidden_field :_destroy, class: 'destroy'
      .form-group.col-md-1.col-xs-6
        label.control-label Actions
        = link_to 'Delete', '##', class: 'btn btn-danger destroy'

app/views/orders/edit.html.slim
.page-header
  h1 Editing order

== render 'form'

=<> link_to 'Show', [@merchant, @order], class: 'btn btn-success'
=<> link_to 'Back', merchant_path(@merchant), class: 'btn btn-default'

app/views/orders/index.html.slim
h1 Listing orders

.table-responsive
  table
    thead
      tr
        th
        th
        th

    tbody
      - @orders.each do |order|
        tr
          td = link_to 'Show', order
          td = link_to 'Edit', edit_order_path(order)
          td = link_to 'Destroy', order, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Order', new_order_path

app/views/orders/new.html.slim
.page-header
  h1 New order

== render 'form'

= link_to 'Back', merchant_path(@merchant), class: 'btn btn-default'

app/views/orders/show.html.slim
.page-header
  h1 订单详情

- if notice
  .alert.alert-info role="alert"= notice

.panel.panel-primary
  .panel-heading 详细信息
  .panel-body
    dl
      dt Name:
      dd = @order.customer.name
  .table-responsive
    table.table
      thead
        th Name
        th Price
        th Quantity
        th Discount
        th Total
      tbody
        - @order.order_items.each do |order_item|
          tr
            td= order_item.product.name
            td= order_item.product.price
            td= order_item.quantity_with_unit
            td= order_item.discount
            td= order_item.total
  .panel-body
    dl
      dt Total cost:
      dd = @order.total_cost
      dt Transacted at:
      dd = I18n.l(@order.transacted_at, format: :long)

=<> link_to 'Edit', edit_merchant_order_path(@merchant, @order), class: 'btn btn-primary'
=<> link_to 'Back', merchant_path(@merchant), class: 'btn btn-default'

.pull-right
  =<> link_to 'Report', report_merchant_order_path(@merchant, @order), class: 'btn btn-primary'
  =<> link_to 'Invoice', invoice_merchant_order_path(@merchant, @order, format: :pdf), class: 'btn btn-success'