config/routes.rb
Rails.application.routes.draw do
  resources :merchants do
    resources :products
    resources :orders do
      collection do
        get :add_order_item
      end

      member do
        get :report
        get :invoice
      end
    end
  end

  mount ChinaCity::Engine => '/china_city'
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  include Addressable

  validates :name, presence: true
  validates :tel, presence: true
  validates :email, presence: true

  has_many :orders, dependent: :destroy
  has_many :products, dependent: :destroy
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

  # GET /merchants
  # GET /merchants.json
  def index
    @merchants = Merchant.all
  end

  # GET /merchants/1
  # GET /merchants/1.json
  def show
    @products = @merchant.products
    @orders = @merchant.orders
  end

  # GET /merchants/new
  def new
    @merchant = Merchant.new
    @merchant.build_address
  end

  # GET /merchants/1/edit
  def edit
    @merchant.address || @merchant.build_address
  end

  # POST /merchants
  # POST /merchants.json
  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merchants/1
  # PATCH/PUT /merchants/1.json
  def update
    respond_to do |format|
      if @merchant.update_attributes(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        @merchant.address || @merchant.build_address

        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.json
  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_merchant
    @merchant = Merchant.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def merchant_params
    params.require(:merchant).permit(:name, :tel, :email, address_attributes: [:zip_code, :detail])
  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.slim
.panel.panel-default
  .panel-body
    = simple_form_for(@merchant) do |f|
      = f.error_notification

      .form-inputs
      = f.input :name
      = f.input :tel
      = f.input :email
      = f.fields_for :address do |address_fields|
        - address = address_fields.object
        - zip_code = address.zip_code.presence || '000000'
        - province = ChinaCity.province(zip_code)
        - city = ChinaCity.city(zip_code)
        - district = address.zip_code
        - provinces  = ChinaCity.list
        - cities     = ChinaCity.list(province)
        - districtes = ChinaCity.list(city)

        .form-group
          label.string.required.control-label for="merchant_name" Address City
          .city-group.row
            .col-sm-4
              = address_fields.select :zip_code, options_for_select(provinces, province), { include_blank: '--省份--' }, { class: 'form-control city-select' }
            .col-sm-4
              = address_fields.select :zip_code, options_for_select(cities, city), { include_blank: '--城市--' }, { class: 'form-control city-select' }
            .col-sm-4
              = address_fields.select :zip_code, options_for_select(districtes, district), { include_blank: '--地区--' }, { class: 'form-control city-select' }
        .form-group
          label.string.required.control-label for="merchant_name" Address Detail
          = address_fields.text_field :detail, class: 'form-control'

      .form-actions
        = f.button :submit, class: 'btn btn-primary'

app/views/merchants/edit.html.slim
h1 Editing merchant

== render 'form'

=<> link_to 'Show', @merchant, class: 'btn btn-success'
=<> link_to 'Back', merchants_path, class: 'btn btn-default'

app/views/merchants/index.html.slim
.page-header
  h1 Listing merchants


.panel.panel-default
  .table-responsive
    table.table
      thead
        tr
          th Name
          th Tel
          th Email
          th Address
          th Actions

      tbody
        - @merchants.each do |merchant|
          tr
            td = merchant.name
            td = merchant.tel
            td = merchant.email
            td = ChinaCity.get(merchant.address.try(:zip_code), prepend_parent: true)
            td
              =<> link_to 'Show', merchant
              =<> link_to 'Edit', edit_merchant_path(merchant)
              =<> link_to 'Destroy', merchant, data: {:confirm => 'Are you sure?'}, :method => :delete


= link_to 'New Merchant', new_merchant_path, class: 'btn btn-primary'

app/views/merchants/new.html.slim
.page-header
  h1 New merchant

== render 'form'

= link_to 'Back', merchants_path, class: 'btn btn-default'

app/views/merchants/show.html.slim
.page-header
  h1= @merchant.name

- if notice
  .alert.alert-info role="alert"= notice

.panel.panel-primary
  .panel-heading 详细信息
  .panel-body
    dl
      dt Tel:
      dd = @merchant.tel
      dt Email:
      dd = @merchant.email
      dt Address:
      dd = @merchant.full_address

.panel.panel-success
  .panel-heading
    .pull-right
      = link_to 'Add', new_merchant_product_path(@merchant), class: 'btn btn-xs btn-success'
    | 所有商品
  .table-responsive
    table.table
      thead
        tr
          th Name
          th Price
          th Unit
          th Actions
      tbody
        - @products.each do |product|
          tr
            td = product.name
            td = product.price
            td = product.unit
            td
              =<> link_to 'Show', [@merchant, product]
              =<> link_to 'Edit', edit_merchant_product_path(@merchant, product)
              =<> link_to 'Destroy', [@merchant, product], data: {:confirm => 'Are you sure?'}, :method => :delete

.panel.panel-success
  .panel-heading
    .pull-right
      = link_to 'New', new_merchant_order_path(@merchant), class: 'btn btn-xs btn-success'
    | 所有订单
  .table-responsive
    table.table
      thead
        tr
          th Customer
          th Total Cost
          th Transacted at
          th Actions
      tbody
        - @orders.each do |order|
          tr
            td = order.customer.name
            td = order.total_cost
            td = I18n.l(order.transacted_at, format: :long)
            td
              =<> link_to 'Show', [@merchant, order]
              =<> link_to 'Edit', edit_merchant_order_path(@merchant, order)
              =<> link_to 'Destroy', [@merchant, order], data: {:confirm => 'Are you sure?'}, :method => :delete

footer.footer
  =<> link_to 'Edit', edit_merchant_path(@merchant), class: 'btn btn-primary'
  =<> link_to 'Back', merchants_path, class: 'btn btn-default'