config/routes.rb
Rails.application.routes.draw do
  resources :merchants do
    resources :products
    resources :orders do
      collection do
        get :add_order_item
      end

      member do
        get :report
        get :invoice
      end
    end
  end

  mount ChinaCity::Engine => '/china_city'
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :merchant
  has_many :order_items, dependent: :destroy

  validates :name, presence: true
  validates :price, presence: true
  validates :unit, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_merchant
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = @merchant.products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = @merchant.products.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = @merchant.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [@merchant, @product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: [@merchant, @product] }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update_attributes(product_params)
        format.html { redirect_to [@merchant, @product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: [@merchant, @product] }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to merchant_url(@merchant), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_merchant
    @merchant = Merchant.find(params[:merchant_id])
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :price, :unit)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.slim
.panel.panel-default
  .panel-body
    = simple_form_for([@merchant, @product]) do |f|
      = f.error_notification

      .form-inputs
      = f.input :name
      = f.input :price
      = f.input :unit

      .form-actions
        = f.button :submit, class: 'btn btn-primary'

app/views/products/edit.html.slim
.page-header
  h1= @merchant.name

== render 'form'

=<> link_to 'Show', [@merchant, @product], class: 'btn btn-success'
=<> link_to 'Back', merchant_path(@merchant), class: 'btn btn-default'

app/views/products/index.html.slim
h1 Listing products

table
  thead
    tr
      th
      th
      th

  tbody
    - @products.each do |product|
      tr
        td = link_to 'Show', product
        td = link_to 'Edit', edit_product_path(product)
        td = link_to 'Destroy', product, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Product', new_product_path

app/views/products/new.html.slim
.page-header
  h1 New product

== render 'form'

= link_to 'Back', merchant_path(@merchant), class: 'btn btn-default'

app/views/products/show.html.slim
.page-header
  h1= @product.name

- if notice
  .alert.alert-info role="alert"= notice

.panel.panel-primary
  .panel-heading 详细信息
  .panel-body
    dl
      dt Name:
      dd = @product.name
      dt Price:
      dd = @product.price
      dt Unit:
      dd = @product.unit

=<> link_to 'Edit', edit_merchant_product_path(@merchant, @product), class: 'btn btn-primary'
=<> link_to 'Back', merchant_path(@merchant), class: 'btn btn-default'